---
- name: Create Static Website
  hosts: all
  become: true
  tasks:
  - name: Install Apache on CentOS
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Install apache httpd  (state=present is optional)
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    
  - name: Start Apache and enable on boot
    systemd:
      name: httpd
      state: started
      enabled: yes
  - name: Install Unzip
    yum:
      name: unzip
      state: present
  - name: Start service and enable
    get_url:
      url: "https://www.free-css.com/assets/files/free-css-templates/download/page291/carserv.zip"
      dest: "/var/www/html/carserv.zip"
  - name: Unzip carserv.zip
    unarchive:
      src: /var/www/html/carserv.zip
      dest: /var/www/html/
      remote_src: true
      extra_opts: '-o'
      
  - name Move files
    shell: "mv /var/www/html/car-repair-html-template/* /var/www/html/"